### ISSUE TITLE
cx的我花了一天整出来了，但是有预约时长四小时的限制，怎么能突破限制？？？

### ISSUE THREAD

**Issue by Doone-skser** [lizazacn/WFULIB2.0#2]
如果有理解请联系我sgvfhv@163.com，谢谢

**Comment by lizazacn** [comment]
建议抓包看一下失败的返回值，也有可能是多线程并发的问题

**Comment by Doone-skser** [comment]
如果提交的时间大于两小时则会返回“预约时长不超过两小时”，如果提交2小时则只能提交两次，第三次就受限了。

**Comment by lizazacn** [comment]
先人工操作一遍，只要人工操作能够完成的操作，用代码就能实现。尽量百分百还原人工操作的流程

**Comment by Doone-skser** [comment]
人工操作也只能最多4小时。。。

**Comment by Doone-skser** [comment]
我刚刚找到了cx签到暂离和退座的方法了，“https://office.chaoxing.com/data/apps/seat/sign?id=seatReserve.id”其中sign是签到，替换成leave是暂离，替换成signback是退座。seatReserve通过“https://office.chaoxing.com/data/apps/seat/reserve/info?id=6296&seatNum=148”获取

**Comment by lizazacn** [comment]
我之前时顺序预约不会有4小时限制，但是不能使用多线程，如果使用多线程的话会时不时的出现四小时限制。

**Comment by Doone-skser** [comment]
我也没使用多线程，这是什么原因呢？

**Comment by lizazacn** [comment]
这可能是他的系统就有四小时限制

**Comment by lizazacn** [comment]
这是我年前的预约逻辑：
`func OrderTodaySeat(info *UserInfo, day string) {
	var timeSlotArray [7]*OrderTimeSlot = [7]*OrderTimeSlot{
		&OrderTimeSlot{
			StartTime: "8:00",
			EndTime: "10:00",
		},
		&OrderTimeSlot{
			StartTime: "10:00",
			EndTime: "12:00",
		},
		&OrderTimeSlot{
			StartTime: "12:00",
			EndTime: "14:00",
		},
		&OrderTimeSlot{
			StartTime: "14:00",
			EndTime: "16:00",
		},
		&OrderTimeSlot{
			StartTime: "16:00",
			EndTime: "18:00",
		},
		&OrderTimeSlot{
			StartTime: "18:00",
			EndTime: "20:00",
		},
		&OrderTimeSlot{
			StartTime: "20:00",
			EndTime: "21:00",
		},
	}
	//quitChan := make(chan bool, 7)
	for i := range timeSlotArray{
		lib := LibraryInit()
		lib.userInfo = info
		token := lib.getToken(info.RoomId, day)
		lib.OrderSeat(info.RoomId, timeSlotArray[i].StartTime, timeSlotArray[i].EndTime, day, info.SeatId, token)
	}
}`

**Comment by lizazacn** [comment]
你可以取这个仓库看一下 源码：https://github.com/lizazacn/go-wfulib.git

**Comment by Doone-skser** [comment]
仓库404了

**Comment by lizazacn** [comment]
之前仓库私有了，现在开放了

**Comment by Doone-skser** [comment]
fidEnc=35bbd135397006a8这个值怎么获得的？如果学校变了 这个值就得从新抓很麻烦呀

**Comment by lizazacn** [comment]
这个是拦截app端的请求得到的，如果换了的话只能重新抓，但是这个值根网站是绑定的不太会轻易换。你可以尝试在个人中心页模拟手机请求获取这个链接，但是我没有真正的去试这个方式。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Doone ***@***.***&gt;
发送时间: 2022年2月27日 16:28
收件人: lizazacn/WFULIB2.0 ***@***.***&gt;
抄送: LGQ ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [lizazacn/WFULIB2.0] cx的我花了一天整出来了，但是有预约时长四小时的限制，怎么能突破限制？？？ (Issue #2)





 
fidEnc=35bbd135397006a8这个值怎么获得的？如果学校变了 这个值就得从新抓很麻烦呀
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Doone-skser** [comment]
我用fiddler设置手机代理，但它不能抓到登陆时发送的请求，有没有好的手机抓包工具能破解这点呢？

**Comment by lizazacn** [comment]
你可以在电脑上用模拟器抓包手机上的话有一个橙色的软件我忘记叫啥名了，软件本身有代理监测机制

**Comment by Doone-skser** [comment]
我通过web端的切换单位时会向’i.chaoxing.com/base/cacheUserOrg’发送时间找到了fid，再配合首页‘uc.chaoxing.com/mobileSet/homePage’的mappid，此时cookies里面会生成incode（'wfwIncode'的键值），再与‘'v1.chaoxing.com/mobile/openRecentApp?incode={self.incode}&mappId={self.mappid}'’就可以在302的location里面找到fidEnc值就是35bbd135397006a8也是deptIdEnc的值，至此所有账号都可以获取到对应的座位信息啦。
